services:
  - type: web
    name: world-of-books-api
    rootDir: backend
    buildCommand: npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 3001
